#!/usr/bin/env python

from __future__ import print_function, division

import sys
from util import template

if sys.version_info < (2, 6):
  print("You must use Python version 2.6 or higher")
  sys.exit(-1)


def main():
    ns = template.Template()
    with open("Makefile", "wb") as f:
      print(ns.expand_file("Makefile.in"), file=f)

if __name__ == '__main__':
    main()
