#!/usr/bin/env python2.6

from __future__ import print_function, division

import sys
from util import template


def main():
    ns = template.Template()
    with open("Makefile", "wb") as f:
      print(ns.expand_file("Makefile.in"), file=f)

if __name__ == '__main__':
    main()
